# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Sun Aug  8 15:42:11 2010
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(888, 704)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.recentButton = QtGui.QPushButton(self.centralwidget)
        self.recentButton.setCheckable(True)
        self.recentButton.setAutoExclusive(True)
        self.recentButton.setObjectName("recentButton")
        self.horizontalLayout.addWidget(self.recentButton)
        self.queueButton = QtGui.QPushButton(self.centralwidget)
        self.queueButton.setCheckable(True)
        self.queueButton.setAutoExclusive(True)
        self.queueButton.setObjectName("queueButton")
        self.horizontalLayout.addWidget(self.queueButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.recentScroll = QtGui.QScrollArea(self.centralwidget)
        self.recentScroll.setWidgetResizable(True)
        self.recentScroll.setObjectName("recentScroll")
        self.recentContents = QtGui.QWidget(self.recentScroll)
        self.recentContents.setGeometry(QtCore.QRect(0, 0, 868, 317))
        self.recentContents.setObjectName("recentContents")
        self.recentLayout = QtGui.QVBoxLayout(self.recentContents)
        self.recentLayout.setMargin(0)
        self.recentLayout.setObjectName("recentLayout")
        spacerItem = QtGui.QSpacerItem(20, 279, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.recentLayout.addItem(spacerItem)
        self.recentScroll.setWidget(self.recentContents)
        self.verticalLayout.addWidget(self.recentScroll)
        self.queueScroll = QtGui.QScrollArea(self.centralwidget)
        self.queueScroll.setWidgetResizable(True)
        self.queueScroll.setObjectName("queueScroll")
        self.queueContents = QtGui.QWidget(self.queueScroll)
        self.queueContents.setGeometry(QtCore.QRect(0, 0, 868, 316))
        self.queueContents.setObjectName("queueContents")
        self.queueLayout = QtGui.QVBoxLayout(self.queueContents)
        self.queueLayout.setMargin(0)
        self.queueLayout.setObjectName("queueLayout")
        spacerItem1 = QtGui.QSpacerItem(20, 278, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.queueLayout.addItem(spacerItem1)
        self.queueScroll.setWidget(self.queueContents)
        self.verticalLayout.addWidget(self.queueScroll)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 888, 23))
        self.menubar.setObjectName("menubar")
        self.menuFremantle = QtGui.QMenu(self.menubar)
        self.menuFremantle.setObjectName("menuFremantle")
        MainWindow.setMenuBar(self.menubar)
        self.actionSettings = QtGui.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionAbout_Qt = QtGui.QAction(MainWindow)
        self.actionAbout_Qt.setObjectName("actionAbout_Qt")
        self.actionReload_repository_data = QtGui.QAction(MainWindow)
        self.actionReload_repository_data.setObjectName("actionReload_repository_data")
        self.menuFremantle.addAction(self.actionSettings)
        self.menuFremantle.addAction(self.actionReload_repository_data)
        self.menuFremantle.addAction(self.actionAbout)
        self.menuFremantle.addAction(self.actionAbout_Qt)
        self.menubar.addAction(self.menuFremantle.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "KISStester", None, QtGui.QApplication.UnicodeUTF8))
        self.recentButton.setText(QtGui.QApplication.translate("MainWindow", "Already installed", None, QtGui.QApplication.UnicodeUTF8))
        self.queueButton.setText(QtGui.QApplication.translate("MainWindow", "Complete QA Queue", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFremantle.setTitle(QtGui.QApplication.translate("MainWindow", "Fremantle", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSettings.setText(QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_Qt.setText(QtGui.QApplication.translate("MainWindow", "About Qt", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReload_repository_data.setText(QtGui.QApplication.translate("MainWindow", "Reload repository data", None, QtGui.QApplication.UnicodeUTF8))

